### ISSUE TITLE
Entering Space breaks input

### ISSUE THREAD

**Issue by maxwelladapoe** [lucasnevespereira/go-gituser#11]
**Describe the bug**
Adding a space in the username it breaks the input on Mac.
<img width="568" alt="image" src="https://github.com/lucasnevespereira/go-gituser/assets/41029340/070e0697-bc97-4a80-a9e6-e95471689ea4">

**To Reproduce**
1. Run gituser setup
2. Enter a username which contains a space
3. See error

**Expected behavior**
to accept username with spaces

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma

**Comment by lucasnevespereira** [comment]
Hello @maxwelladapoe, thank you for using gituser and bringing this to my attention.

The username is supposed to be a GitHub username and those do not include spaces. That's why gituser is not able to process usernames with spaces.

However, I understand that the error message you're receiving might not be clear enough about this.
I'm going to work on enhancing error handling to provide a more explicit error message.

In the meantime, please ensure that the username you're entering does not contain any spaces.
